import type { OverrideToken } from 'antd/es/theme/interface'
import { palette } from '../palette'

export const buttonTokens: OverrideToken['Button'] = {
  colorPrimary:             palette.primary600,
  colorPrimaryHover:        palette.primary700,
  colorPrimaryActive:       palette.primary800,
  borderRadius:             8,
  controlHeight:            36,
  controlHeightSM:          28,
  paddingInline:            16,
  paddingInlineSM:          8,
  paddingInlineLG:          16,
  primaryShadow:            '0px 1px 4px 0px rgba(11,43,105,0.24)',
  defaultShadow:            '0px 2px 4px 0px rgba(115,122,132,0.12)',
  dangerShadow:             '0px 1px 4px 0px rgba(204,94,94,0.24)',
  defaultBg:                palette.translucentSurface32,
  defaultBorderColor:       palette.whiteAlpha30,
  defaultColor:             palette.neutral900,
  defaultHoverBg:           palette.disabledBg,
  defaultHoverColor:        palette.neutral900,
  defaultHoverBorderColor:  palette.whiteAlpha30,
  defaultActiveBg:          palette.translucentSurface32,
  defaultActiveColor:       palette.neutral900,
  defaultActiveBorderColor: palette.primaryAlpha35,
  defaultBgDisabled:        palette.disabledBg,
  primaryColor:             palette.neutral0,
  dangerColor:              palette.white,
  fontWeight:               500,
  iconGap:                  8,
  contentFontSize:          14,
  contentFontSizeLG:        16,
  contentFontSizeSM:        14,
  onlyIconSize:             24,
  onlyIconSizeLG:           24,
  onlyIconSizeSM:           16,
}
